### ISSUE TITLE
optimization suggestions

### ISSUE THREAD

**Issue by mygoare** [yzsolo/react-native-scrolltotop#3]
First, good job! Some suggestions below:
- I think it is not a good idea to hide and show the `ScrollTopView` like this
  
  ```
  {this.state.isShowToTop?<ScrollTopView root={this} ></ScrollTopView>:null}
  ```
  
  You can make `thist.state.isShowToTop` as a props of `ScrollTopView` to control and change its status.
- I also noticed the `ScrollTopView` has a `setOpacityTo` method, this is a really good way to use to optimize the user experience in your component.

**Comment by yzsolo** [comment]
@mygoare Thank you for your suggestion, but `state` is the best way to control the hide or show of the component, it is like a state machine. and the opacity of the component is because i uesed `TouchableOpacity` as the button. Anyway, thank you for your praise，I will keep moving.:smile:
